refs 22_04_implement_video_player_done
DoanVanToan/EnglishConversation pull request #19
Opened 2017-12-19 01:26 UTC by TheVinhLuong

2017-12-19 01:34 UTC, daolq3012 requested changes
Pls check my comment!

2017-12-19 01:34 UTC, daolq3012 commented on app/src/main/AndroidManifest.xml
> +</manifest>
we must add blank line when end of file. so pls keep old code

2017-12-19 01:34 UTC, daolq3012 commented on app/src/main/java/com/framgia/englishconversation/screen/createPost/CreatePostViewModel.java
> +
remove blank line

2017-12-19 01:44 UTC, fs-sournary commented on app/src/main/java/com/framgia/englishconversation/screen/videoDetail/VideoDetailPresenter.java
> +    private static final String TAG = VideoDetailPresenter.class.getName();
remove TAG

2017-12-19 01:44 UTC, fs-sournary commented on app/src/main/java/com/framgia/englishconversation/screen/videoDetail/VideoDetailViewModel.java
> +        if (Util.SDK_INT > 23) {
Hard code

2017-12-19 01:44 UTC, fs-sournary commented on app/src/main/java/com/framgia/englishconversation/screen/videoDetail/VideoDetailViewModel.java
> +        if ((Util.SDK_INT <= 23) || mSimpleExoPlayer == null) {
Hard code

2017-12-19 01:44 UTC, fs-sournary commented on app/src/main/java/com/framgia/englishconversation/screen/videoDetail/VideoDetailViewModel.java
> +        if (Util.SDK_INT <= 23) {
Hard code

2017-12-19 01:44 UTC, fs-sournary commented on app/src/main/java/com/framgia/englishconversation/screen/videoDetail/VideoDetailViewModel.java
> +        if (Util.SDK_INT > 23) {
Hard code

2017-12-19 01:44 UTC, fs-sournary commented on app/src/main/java/com/framgia/englishconversation/screen/videoDetail/VideoDetailViewModel.java
> +        Uri uri = Uri.parse(mTimelineModel.getMedias().get(0).getUrl());
Hard code

2017-12-19 01:44 UTC, fs-sournary commented on app/src/main/java/com/framgia/englishconversation/utils/Constant.java
> +
remove blank line

2017-12-19 01:54 UTC, TheVinhLuong commented on app/src/main/java/com/framgia/englishconversation/screen/videoDetail/VideoDetailViewModel.java
> +        Uri uri = Uri.parse(mTimelineModel.getMedias().get(0).getUrl());
i can't see where

2017-12-19 02:02 UTC, daolq3012 commented on app/src/main/java/com/framgia/englishconversation/screen/videoDetail/VideoDetailViewModel.java
> +        Uri uri = Uri.parse(mTimelineModel.getMedias().get(0).getUrl());
check !=null in here

2017-12-20 01:26 UTC, DoanVanToan commented on app/src/main/res/layout/custom_video_playback_controller.xml
> +
remove bl

2017-12-20 01:26 UTC, DoanVanToan commented on app/src/main/res/layout/custom_video_playback_controller.xml
> +
remove bl

2017-12-20 01:26 UTC, DoanVanToan commented on app/src/main/res/layout/custom_video_playback_controller.xml
> +            android:textColor="#FFBEBEBE"
hardcode

2017-12-20 01:26 UTC, DoanVanToan commented on app/src/main/res/layout/custom_video_playback_controller.xml
> +            android:textColor="#FFBEBEBE"
hardcode

2017-12-20 01:38 UTC, DoanVanToan approved these changes

2017-12-20 01:39 UTC, merged